version: '3.8'

//you can reffer this docs:-https://projects.100xdevs.com/tracks/docker-2/docker-2-13
services:
  backend:
    build: 
     context: ./backend
    image: dhirukumar/dockerpaytm-backend:latest
    ports:
      - "3000:3000"
    networks:
      - dhiru
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - dhiru
    volumes:
      - mongo_data:/data/db

  frontend:
    build: ./frontend
    image: dhirukumar/dockerpaytm-frontend:latest
    ports:
      - "5173:5173"
    networks:
      - dhiru

networks:
  dhiru:
    driver: bridge

volumes:
  mongo_data:
    driver: local
